### ISSUE TITLE
TileTypeIdx makes sense as enum or similar structure

### ISSUE THREAD

**Issue by Kartoffelsaft** [OvermindDL1/over_simple_game_1#1]
Feel free to close this issue if you know there is a reason for `TileTypeIdx` being type defined to `u16`. Though I would be curious to know the reason.

The way it looks to me, TileTypeIdx seems to be used like it's an enum with a bunch of initialization and accessor functions. A lot of the code surrounding it seems to be converting from `String` to `TileTypeIdx`. This sort of thing only really seems viable to me if you want to either have it dynamic enough to where the id is done at runtime, which seems odd to me.

What I think makes sense is one of two things:

1. if core/ is just for this game
``` rust
enum TileId {
    Water = 0,
    Grass = 1,
    // ...
}
// ...
impl FromStr for TileId { /* ... */ }
```

2. if core/ is meant to be very generic, and mostly defined by game/
``` rust
struct TileId<T: FromStr, ToU16 /* or whatever rust uses to convert to int. I couldn't find anything */> {
    id: T
}
```

maybe there is a `type A = B` that would accomplish #2, but I find myself using that keyword rarely so I wouldn't know.

**Comment by OvermindDL1** [comment]
You're right, `TileIdx` was mostly written because I was still deciding what size ID the TileType Index should be and I didn't want to change 40 locations every time I wanted to test something else, but it's well settled now and it should become a proper type, probably via TypedIndexMap.  I'll look into fixing that soon.  :-)

**Comment by Kartoffelsaft** [comment]
Closing this as it appears it was changed in commit cb3109c
